// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members


import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm4WUp9mnwJ6O1KNnhPxcb1utB16MD3io',
    appId: '1:611951286348:web:c94efb89455196480dfce9',
    messagingSenderId: '611951286348',
    projectId: 'habertakipapp',
    authDomain: 'habertakipapp.firebaseapp.com',
    storageBucket: 'habertakipapp.appspot.com',
    measurementId: 'G-TS3KVVEQ09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzKpgz1gnqg4JXF3gs_KbPDNQ7Ml9QmLY',
    appId: '1:611951286348:android:0299c84a553fb39a0dfce9',
    messagingSenderId: '611951286348',
    projectId: 'habertakipapp',
    storageBucket: 'habertakipapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsst6eDON_3WotaTxQPv3vacmLDTB0jag',
    appId: '1:611951286348:ios:9d74e811427e9c4e0dfce9',
    messagingSenderId: '611951286348',
    projectId: 'habertakipapp',
    storageBucket: 'habertakipapp.appspot.com',
    iosClientId: '611951286348-shr86d49g15dlou14a8edkgih95oocgm.apps.googleusercontent.com',
    iosBundleId: 'com.example.habertakipapp',
  );
}
